/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify your block.json and rerun the script.
 */

export interface BlockAttributes {
	lightThemeBgColor: string;
	darkThemeBgColor: string;
	lightThemeTextColor: string;
	darkThemeTextColor: string;
}
